#ifndef ARCHIVEIDS_H_
#define ARCHIVEIDS_H_

/*
 * This file was generated by the JCID2 utility.
 * Do not alter by hand. To make a change, adjust the
 * corresponding entry in the configuration file.
 */

#define ARC_XML 0x6a07e2e7
#define ARC_SHADERS 0x4a0d59c6

#endif // ARCHIVEIDS_H_