#ifndef RESIDS_H_
#define RESIDS_H_

/*
 * This file was generated by the JCID2 utility.
 * Do not alter by hand. To make a change, adjust the
 * corresponding entry in the configuration file.
 */

#define RES_TILE_FRAGMENT_SHADER 0xcef2db95
#define RES_GRAPHICS_CONFIG 0xdb51f7be
#define null 0x2d53fcc9
#define RES_OPTIONS 0x3f8dd6d1
#define RES_TILE_VERTEX_SHADER 0x75c7a46
#define RES_KEY_MAP 0x22a41be

#endif // RESIDS_H_